# Generated by Django 5.1.4 on 2025-01-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_address_account_otp_account_otp_expiry"),
        ("advertisement", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="favorite_advertisement",
            field=models.ManyToManyField(to="advertisement.advertisement"),
        ),
    ]
