# Generated by Django 5.1.4 on 2025-01-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'advertisement', 'verbose_name_plural': 'advertisements'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisement.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'RESOLVED'), (3, 'SOLD')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(verbose_name='reason'),
        ),
    ]
