# Generated by Django 5.1.4 on 2025-01-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0005_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="main_picture",
        ),
    ]
